DELETE FROM StreamPosition;

DROP TABLE DayRegister;
DROP TABLE MonthRegister;
DROP TABLE YearRegister;
DROP INDEX DayReadingIX;
DROP INDEX MonthReadingIX;
DROP INDEX YearReadingIX;
DROP TABLE DayReading;
DROP TABLE MonthReading;
DROP TABLE YearReading;

DROP INDEX LiveReadingIX;

ALTER TABLE LiveRegister RENAME TO LiveRegisterOld;
ALTER TABLE LiveReading RENAME TO LiveReadingOld;

CREATE TABLE LiveReading (Id INTEGER PRIMARY KEY, Label NVARCHAR(50) NOT NULL, DeviceId NVARCHAR(50) NOT NULL, Timestamp DATETIME NOT NULL);
CREATE INDEX LiveReadingIX ON LiveReading (Timestamp DESC);
CREATE TABLE LiveRegister (ReadingId INTEGER NOT NULL, ObisCode INTEGER NOT NULL, Value INTEGER NOT NULL, Scale INTEGER NOT NULL, Unit INTEGER NOT NULL, PRIMARY KEY(ReadingId,ObisCode), FOREIGN KEY (ReadingId) REFERENCES LiveReading(Id)) WITHOUT ROWID;

INSERT INTO LiveReading (Id, Label, DeviceId, Timestamp) SELECT Id, Label, SerialNumber, Timestamp FROM LiveReadingOld;
INSERT INTO LiveRegister (ReadingId, ObisCode, Value, Scale, Unit) SELECT ReadingId, ObisCode, Value, Scale, Unit FROM LiveRegisterOld;

DROP TABLE LiveRegisterOld;
DROP TABLE LiveReadingOld;

CREATE TABLE DayReading (Id INTEGER PRIMARY KEY, Label NVARCHAR(50) NOT NULL, DeviceId NVARCHAR(50) NOT NULL, Timestamp DATETIME NOT NULL);
CREATE INDEX DayReadingIX ON DayReading (Timestamp DESC);
CREATE TABLE DayRegister (ReadingId INTEGER NOT NULL, ObisCode INTEGER NOT NULL, Value INTEGER NOT NULL, Scale INTEGER NOT NULL, Unit INTEGER NOT NULL, PRIMARY KEY(ReadingId,ObisCode), FOREIGN KEY (ReadingId) REFERENCES DayReading(Id)) WITHOUT ROWID;

CREATE TABLE MonthReading (Id INTEGER PRIMARY KEY, Label NVARCHAR(50) NOT NULL, DeviceId NVARCHAR(50) NOT NULL, Timestamp DATETIME NOT NULL);
CREATE INDEX MonthReadingIX ON MonthReading (Timestamp DESC);
CREATE TABLE MonthRegister (ReadingId INTEGER NOT NULL, ObisCode INTEGER NOT NULL, Value INTEGER NOT NULL, Scale INTEGER NOT NULL, Unit INTEGER NOT NULL, PRIMARY KEY(ReadingId,ObisCode), FOREIGN KEY (ReadingId) REFERENCES MonthReading(Id)) WITHOUT ROWID;

CREATE TABLE YearReading (Id INTEGER PRIMARY KEY, Label NVARCHAR(50) NOT NULL, DeviceId NVARCHAR(50) NOT NULL, Timestamp DATETIME NOT NULL);
CREATE INDEX YearReadingIX ON YearReading (Timestamp DESC);
CREATE TABLE YearRegister (ReadingId INTEGER NOT NULL, ObisCode INTEGER NOT NULL, Value INTEGER NOT NULL, Scale INTEGER NOT NULL, Unit INTEGER NOT NULL, PRIMARY KEY(ReadingId,ObisCode), FOREIGN KEY (ReadingId) REFERENCES YearReading(Id)) WITHOUT ROWID;