#!/bin/bash
### BEGIN INIT INFO
# Provides:          PowerView
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       This file should be placed in /etc/init.d and should be used to construct runlevel scripts.
### END INIT INFO

start() {
	PID=$(pgrep -d " " -f .*mono.*PowerView.exe.*)
	if [ -z "$PID" ]
	then
  		mono /opt/PowerView/PowerView.exe
	else
  		echo PowerView already started
	fi
}

stop() {
	PID=$(pgrep -d " " -f .*mono.*PowerView.exe.*)
	if [ -z "$PID" ]
	then
  		echo PowerView already stopped
	else
  		kill -SIGTERM $PID
  		echo Stop signal sent to PowerView
	fi
}

# Check to see if we are running as root first.
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
	    sleep 2s
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac