CREATE TABLE Import (Id INTEGER PRIMARY KEY, Label NVARCHAR(255) NOT NULL, Channel NVARCHAR(255) NOT NULL, Currency INT NOT NULL, FromTimestamp DATETIME NOT NULL, CurrentTimestamp DATETIME NULL, Enabled INT NOT NULL);
CREATE UNIQUE INDEX ImportIX ON Import (Label);
