export let settingsProfileGraphsSeries = {
   "items":[
      {
         "period":"day",
         "label":"Conservatory",
         "obisCode":"15.1.223.0.0.255"
      },
      {
         "period":"day",
         "label":"Conservatory",
         "obisCode":"15.1.223.0.2.255"
      },
      {
         "period":"day",
         "label":"Heater",
         "obisCode":"1.0.1.7.0.255"
      },
      {
         "period":"day",
         "label":"Heater",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"day",
         "label":"Inverter",
         "obisCode":"1.0.2.7.0.255"
      },
      {
         "period":"day",
         "label":"Inverter",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.1.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.2.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.21.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.22.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.41.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.42.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.61.7.0.255"
      },
      {
         "period":"day",
         "label":"Main",
         "obisCode":"1.0.62.7.0.255"
      },
      {
         "period":"day",
         "label":"Relay",
         "obisCode":"0.1.96.3.10.255"
      },
      {
         "period":"day",
         "label":"Water",
         "obisCode":"8.66.1.0.0.255"
      },
      {
         "period":"day",
         "label":"Water",
         "obisCode":"8.0.2.0.0.255"
      },
      {
         "period":"month",
         "label":"Heater",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"month",
         "label":"Heater",
         "obisCode":"1.65.1.8.0.255"
      },
      {
         "period":"month",
         "label":"Inverter",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"month",
         "label":"Inverter",
         "obisCode":"1.65.2.8.0.255"
      },
      {
         "period":"month",
         "label":"Main",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"month",
         "label":"Main",
         "obisCode":"1.65.1.8.0.255"
      },
      {
         "period":"month",
         "label":"Main",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"month",
         "label":"Main",
         "obisCode":"1.65.2.8.0.255"
      },
      {
         "period":"month",
         "label":"Water",
         "obisCode":"8.66.1.0.0.255"
      },
      {
         "period":"month",
         "label":"Water",
         "obisCode":"8.65.1.0.0.255"
      },
      {
         "period":"year",
         "label":"Heater",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"year",
         "label":"Heater",
         "obisCode":"1.65.1.8.0.255"
      },
      {
         "period":"year",
         "label":"Inverter",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"year",
         "label":"Inverter",
         "obisCode":"1.65.2.8.0.255"
      },
      {
         "period":"year",
         "label":"Main",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"year",
         "label":"Main",
         "obisCode":"1.65.1.8.0.255"
      },
      {
         "period":"year",
         "label":"Main",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"year",
         "label":"Main",
         "obisCode":"1.65.2.8.0.255"
      },
      {
         "period":"year",
         "label":"Water",
         "obisCode":"8.66.1.0.0.255"
      },
      {
         "period":"year",
         "label":"Water",
         "obisCode":"8.65.1.0.0.255"
      },
      {
         "period":"decade",
         "label":"Heater",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"decade",
         "label":"Heater",
         "obisCode":"1.65.1.8.0.255"
      },
      {
         "period":"decade",
         "label":"Inverter",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"decade",
         "label":"Inverter",
         "obisCode":"1.65.2.8.0.255"
      },
      {
         "period":"decade",
         "label":"Main",
         "obisCode":"1.66.1.8.0.255"
      },
      {
         "period":"decade",
         "label":"Main",
         "obisCode":"1.65.1.8.0.255"
      },
      {
         "period":"decade",
         "label":"Main",
         "obisCode":"1.66.2.8.0.255"
      },
      {
         "period":"decade",
         "label":"Main",
         "obisCode":"1.65.2.8.0.255"
      },
      {
         "period":"decade",
         "label":"Water",
         "obisCode":"8.66.1.0.0.255"
      },
      {
         "period":"decade",
         "label":"Water",
         "obisCode":"8.65.1.0.0.255"
      }      
   ]
}
;