export let settingsProfileGraphs = {
   "items":[
      {
         "period":"day",
         "page":"A page",
         "title":"Water",
         "interval":"5-minutes",
         "rank":2,
         "series":[
            {
               "label":"Water",
               "obisCode":"8.1.1.0.0.200"
            },
            {
               "label":"Water",
               "obisCode":"8.1.2.0.0.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"Other page",
         "title":"El Import",
         "interval":"5-minutes",
         "rank":3,
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.1.1.7.0.255"
            },
            {
               "label":"Heater",
               "obisCode":"1.1.1.8.0.200"
            },
            {
               "label":"Main",
               "obisCode":"1.1.1.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.1.8.0.200"
            }
         ]
      },
      {
         "period":"day",
         "page":"Other page",
         "title":"El Export",
         "interval":"5-minutes",
         "rank":5,
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.1.2.7.0.255"
            },
            {
               "label":"Inverter",
               "obisCode":"1.1.2.8.0.200"
            },
            {
               "label":"Main",
               "obisCode":"1.1.2.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.2.8.0.200"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"Water",
         "interval":"1-days",
         "rank":9,
         "series":[
            {
               "label":"Water",
               "obisCode":"8.1.1.0.0.200"
            },
            {
               "label":"Water",
               "obisCode":"8.1.1.0.0.100"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"El Net",
         "interval":"1-days",
         "rank":10,
         "series":[
            {
               "label":"Family",
               "obisCode":"1.210.1.8.0.200"
            },
            {
               "label":"Family",
               "obisCode":"1.210.1.8.0.100"
            },
            {
               "label":"Family",
               "obisCode":"1.220.1.8.0.200"
            },
            {
               "label":"Family",
               "obisCode":"1.220.1.8.0.100"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"El Import",
         "interval":"1-days",
         "rank":11,
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.1.1.8.0.200"
            },
            {
               "label":"Heater",
               "obisCode":"1.1.1.8.0.100"
            },
            {
               "label":"Main",
               "obisCode":"1.1.1.8.0.200"
            },
            {
               "label":"Main",
               "obisCode":"1.1.1.8.0.100"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"El Export",
         "interval":"1-days",
         "rank":12,
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.1.2.8.0.200"
            },
            {
               "label":"Inverter",
               "obisCode":"1.1.2.8.0.100"
            },
            {
               "label":"Main",
               "obisCode":"1.1.2.8.0.200"
            },
            {
               "label":"Main",
               "obisCode":"1.1.2.8.0.100"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"Water",
         "interval":"1-months",
         "rank":13,
         "series":[
            {
               "label":"Water",
               "obisCode":"8.1.1.0.0.200"
            },
            {
               "label":"Water",
               "obisCode":"8.1.1.0.0.100"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"El Net",
         "interval":"1-months",
         "rank":14,
         "series":[
            {
               "label":"Family",
               "obisCode":"1.210.1.8.0.200"
            },
            {
               "label":"Family",
               "obisCode":"1.210.1.8.0.100"
            },
            {
               "label":"Family",
               "obisCode":"1.220.1.8.0.200"
            },
            {
               "label":"Family",
               "obisCode":"1.220.1.8.0.100"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"El Import",
         "interval":"1-months",
         "rank":15,
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.1.1.8.0.200"
            },
            {
               "label":"Heater",
               "obisCode":"1.1.1.8.0.100"
            },
            {
               "label":"Main",
               "obisCode":"1.1.1.8.0.200"
            },
            {
               "label":"Main",
               "obisCode":"1.1.1.8.0.100"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"El Export",
         "interval":"1-months",
         "rank":16,
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.1.2.8.0.200"
            },
            {
               "label":"Inverter",
               "obisCode":"1.1.2.8.0.100"
            },
            {
               "label":"Main",
               "obisCode":"1.1.2.8.0.200"
            },
            {
               "label":"Main",
               "obisCode":"1.1.2.8.0.100"
            }
         ]
      },
      {
         "period":"day",
         "page":"",
         "title":"Relay",
         "interval":"5-minutes",
         "rank":20,
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.1.1.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.62.7.0.255"
            },
            {
               "label":"Relay",
               "obisCode":"0.1.96.3.10.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"",
         "title":"El Power",
         "interval":"5-minutes",
         "rank":21,
         "series":[
            {
               "label":"Main",
               "obisCode":"1.1.21.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.22.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.41.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.61.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.1.62.7.0.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"",
         "title":"Conservatory",
         "interval":"5-minutes",
         "rank":22,
         "series":[
            {
               "label":"Conservatory",
               "obisCode":"15.1.223.0.0.255"
            },
            {
               "label":"Conservatory",
               "obisCode":"15.1.223.0.2.255"
            }
         ]
      }
   ]
}
;