export let settingsProfileGraphs = {
   "items":[
      {
         "period":"day",
         "page":"A page",
         "title":"Water",
         "interval":"5-minutes",
         "series":[
            {
               "label":"Water",
               "obisCode":"8.66.1.0.0.255"
            },
            {
               "label":"Water",
               "obisCode":"8.0.2.0.0.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"Other page",
         "title":"El Import",
         "interval":"5-minutes",
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.0.1.7.0.255"
            },
            {
               "label":"Heater",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.1.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.1.8.0.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"Other page",
         "title":"El Export",
         "interval":"5-minutes",
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.0.2.7.0.255"
            },
            {
               "label":"Inverter",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.2.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.2.8.0.255"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"Water",
         "interval":"1-days",
         "series":[
            {
               "label":"Water",
               "obisCode":"8.66.1.0.0.255"
            },
            {
               "label":"Water",
               "obisCode":"8.65.1.0.0.255"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"El Import",
         "interval":"1-days",
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Heater",
               "obisCode":"1.65.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.65.1.8.0.255"
            }
         ]
      },
      {
         "period":"month",
         "page":"",
         "title":"El Export",
         "interval":"1-days",
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Inverter",
               "obisCode":"1.65.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.65.2.8.0.255"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"Water",
         "interval":"1-months",
         "series":[
            {
               "label":"Water",
               "obisCode":"8.66.1.0.0.255"
            },
            {
               "label":"Water",
               "obisCode":"8.65.1.0.0.255"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"El Import",
         "interval":"1-months",
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Heater",
               "obisCode":"1.65.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.65.1.8.0.255"
            }
         ]
      },
      {
         "period":"year",
         "page":"",
         "title":"El Export",
         "interval":"1-months",
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Inverter",
               "obisCode":"1.65.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.65.2.8.0.255"
            }
         ]
      },
      {
         "period":"decade",
         "page":"",
         "title":"Water",
         "interval":"1-years",
         "series":[
            {
               "label":"Water",
               "obisCode":"8.66.1.0.0.255"
            },
            {
               "label":"Water",
               "obisCode":"8.65.1.0.0.255"
            }
         ]
      },
      {
         "period":"decade",
         "page":"",
         "title":"El Import",
         "interval":"1-years",
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Heater",
               "obisCode":"1.65.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.1.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.65.1.8.0.255"
            }
         ]
      },
      {
         "period":"decade",
         "page":"",
         "title":"El Export",
         "interval":"1-years",
         "series":[
            {
               "label":"Inverter",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Inverter",
               "obisCode":"1.65.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.66.2.8.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.65.2.8.0.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"",
         "title":"Relay",
         "interval":"30-minutes",
         "series":[
            {
               "label":"Heater",
               "obisCode":"1.0.1.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.62.7.0.255"
            },
            {
               "label":"Relay",
               "obisCode":"0.1.96.3.10.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"",
         "title":"El Power",
         "interval":"30-minutes",
         "series":[
            {
               "label":"Main",
               "obisCode":"1.0.21.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.22.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.41.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.61.7.0.255"
            },
            {
               "label":"Main",
               "obisCode":"1.0.62.7.0.255"
            }
         ]
      },
      {
         "period":"day",
         "page":"",
         "title":"Conservatory",
         "interval":"30-minutes",
         "series":[
            {
               "label":"Conservatory",
               "obisCode":"15.1.223.0.0.255"
            },
            {
               "label":"Conservatory",
               "obisCode":"15.1.223.0.2.255"
            }
         ]
      }
   ]
}
;