CREATE TABLE LiveReading (Id INTEGER PRIMARY KEY, Label NVARCHAR(10) NOT NULL, Timestamp DATETIME NOT NULL);
CREATE INDEX LiveReadingIX ON LiveReading (Timestamp DESC);

CREATE TABLE LiveRegister (Id INTEGER PRIMARY KEY, ObisCode INTEGER NOT NULL, Value INTEGER NOT NULL, Scale INTEGER NOT NULL, Unit INTEGER NOT NULL, LiveReadingId INTEGER NOT NULL, FOREIGN KEY (LiveReadingId) REFERENCES LiveReading(Id));
CREATE UNIQUE INDEX LiveRegisterIX ON LiveRegister (LiveReadingId, ObisCode);