CREATE TABLE MonthReading (Id INTEGER PRIMARY KEY, Label NVARCHAR(10) NOT NULL, Timestamp DATETIME NOT NULL);
CREATE INDEX MonthReadingIX ON MonthReading (Timestamp DESC);

CREATE TABLE MonthRegister (Id INTEGER PRIMARY KEY, ObisCode INTEGER NOT NULL, Value INTEGER NOT NULL, Scale INTEGER NOT NULL, Unit INTEGER NOT NULL, ReadingId INTEGER NOT NULL, FOREIGN KEY (ReadingId) REFERENCES MonthReading(Id));
CREATE UNIQUE INDEX MonthRegisterIX ON MonthRegister (ReadingId, ObisCode);